### ISSUE TITLE
Compiling on CentOS: CL strings issue

### ISSUE THREAD

**Issue by CloudyOverhead** [gfabieno/SeisCL#1]
While compiling SeisCL on CentOS 7.5.1804, the errors logged in the following file prevent it from completing:
[Console output](https://github.com/gfabieno/SeisCL/files/3672728/out.txt)

The created files appear to be correct, as the contents of the `src` directory after trying to compile shows:
[src](https://github.com/gfabieno/SeisCL/files/3672748/src.zip)

I may be able to debug this issue and push a fix, but I would need guidance as to what causes the issue.

**Comment by gfabieno** [comment]
We are moving to a new version and the problematic kernel is no longer relevant. Please use the CUDACL_simplfy branch for the moment. This branch should be merged into master soon!

**Comment by CloudyOverhead** [comment]
The same issue happened on `CUDACL_simplify`. Commit 3e997dfb39887cc790cbf69f4159cd7cca39852d solves this problem and SeisCL compiles successfully on CentOS.
